### ISSUE TITLE
Voice reputation

### ISSUE THREAD

**Issue by Goldmensch** [RainbowDashLabs/reputation-bot#32]
It should be a way to give reputation to people you have helped in a voice channel. One possibility would be to set a channel where you can thank people in voice with e.g. 
"prefix voice @name" (/rep voice @chojo)

**Comment by RainbowDashLabs** [comment]
This shouldn't be done as a command probably since it would add a command reputation logic for voice but not for text.

The bot currently resolves the last users form the channel which a user could possibly thank. This is called context. This context contains users which can be thanked. We could just log with which users any user on this guild shared a channel recently and add these ppl to the context.
This would allow users to thank a user in any channel even without a present latest message of the receiver.
