### ISSUE TITLE
[Feature Request] Reputation for Nitro Boosters

### ISSUE THREAD

**Issue by isaaclepes** [rainbowdashlabs/reputation-bot#587]
A feature to allow Nitro Boosters to earn reputation for how many times they have boosted the server.

**Comment by yannicklamprecht** [comment]
This request is formulated a little vague.

- Do want a certain amount of reputation once for each boost?
- Do you want to have a reputation multiplier for each time a booster earns reputation. Like original reputation is 1 and when boosting you'll get 2, boosting twice 3 and so on?

I don't have a clue if we support non integer reputation, so 1.2 (1x boost), 1.5 (2x boost) will be supported.

**Comment by rainbowdashlabs** [comment]
The only thing that would kind of be possible would be to add a reputation, plus the amount of current boosters of the person as the reputation was received.
That would be possible to be stored on the side. However it would kind of defeat the purpose of the bot to deliver an honest score on the helpfulness of a user, so that would be quite a low priority issue and also definitely opt in.

**Comment by isaaclepes** [comment]
I didn't realize it would be so complicated. Thanks for reviewing the request :)
